name: CI

on:
  push:
    branches: 
    - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: 'npm install --save-dev typescript'
      - run: 'npm run build'
      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws s3 rm --recursive --exclude "vm/*" --exclude "assets/*" s3://ud2.sh
          aws s3 cp --recursive ./dist s3://ud2.sh
      - name: Purge cache
        uses: jakejarvis/cloudflare-purge-action@v0.3.0
        env: 
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

